apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-volume
      mountPath: /pvc-path
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: my-pvc
