apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
  labels:
    app: sidecar-app
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: "/var/log/nginx"
  - name: adaptor
    image: busybox
    command: ["/bin/sh", "-c", "while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 5; done"]
    volumeMounts:
    - name: workdir
      mountPath: "/var/log/nginx"
  volumes:
  - name: workdir
    emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: sidecar-service
spec:
  type: NodePort
  selector:
    app: sidecar-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30001
