apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox:latest
            command: ["sleep", "1"]
          restartPolicy: Never
