apiVersion: v1
kind: Service
metadata:
    name: my-nodeport
spec:
    type: NodePort
    selector:
        app: ip-app
    ports:
    - name: http
      targetPort: 80
      port: 8080
      nodePort: 30001
