apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: busybox
    image: busybox:latest
    command: ["/bin/sh", "-c"]
    args: ["echo '<html><body><h2>I am from init container</h2></body></html>' > /share_drive/index.html && echo 'Init is completed successfully'"]
    volumeMounts:
    - name: share-drive
      mountPath: "/share_drive"
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: share-drive
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: share-drive
    emptyDir: {}